/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Event = "fill";
export type Symbol = string;
export type Underlyingsymbol = string;
export type Sectype = string;
export type Exchange = string;
export type Op = string;
export type Quantity = number;
export type Avgprice = number;
export type Tradedate = string;
export type Lastfilltime = string;
export type Ordertime = string;
export type Orderid = string;
export type Execids = string[];
export type Account = string;
export type Commission = number;
export type Commissioncurrency = string;
export type Currency = string;
export type Ordertype = string;
export type Fillcount = number;
export type Trades = Fill[];

export interface WebhookPayload {
  trades: Trades;
  [k: string]: unknown;
}
export interface Fill {
  event?: Event;
  symbol: Symbol;
  underlyingSymbol: Underlyingsymbol;
  secType: Sectype;
  exchange: Exchange;
  op: Op;
  quantity: Quantity;
  avgPrice: Avgprice;
  tradeDate: Tradedate;
  lastFillTime: Lastfilltime;
  orderTime: Ordertime;
  orderId: Orderid;
  execIds: Execids;
  account: Account;
  commission: Commission;
  commissionCurrency: Commissioncurrency;
  currency: Currency;
  orderType: Ordertype;
  fillCount: Fillcount;
  [k: string]: unknown;
}
